const mockNews = [
  {
    id: "1",
    title: "AI Breakthrough: New Model Achieves Human-Level Reasoning",
    summary: "Researchers unveil a new AI model that demonstrates unprecedented reasoning capabilities across multiple domains.",
    content: "In a landmark announcement, a team of researchers has unveiled a new artificial intelligence model that demonstrates human-level reasoning across mathematics, science, and logical problem-solving. The model, trained on a diverse dataset, shows remarkable ability to break down complex problems and arrive at solutions step by step.\n\nExperts say this represents a significant leap forward in AI capabilities, potentially transforming fields from healthcare diagnostics to scientific research. The model's architecture introduces novel attention mechanisms that allow it to maintain context over much longer sequences than previous systems.\n\nHowever, some researchers urge caution, noting that while the model excels at structured reasoning tasks, it still struggles with common-sense reasoning and emotional intelligence. The team plans to open-source the model's weights next month.",
    category: "Tech",
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=600&h=400&fit=crop",
    date: "2025-04-09",
    bias: "Neutral",
    mood: "Positive",
    confidence: 95,
    isBreaking: true,
  },
  {
    id: "2",
    title: "Global Climate Summit Reaches Historic Agreement",
    summary: "World leaders commit to unprecedented carbon reduction targets at the annual climate summit.",
    content: "In what environmental groups are calling a watershed moment, representatives from 195 nations have agreed to binding carbon emission targets that exceed previous commitments by 40%. The agreement, reached after marathon negotiations, includes provisions for financial support to developing nations transitioning away from fossil fuels.\n\nThe deal establishes a new global carbon market and sets intermediate milestones for 2030 and 2035. Key provisions include mandatory reporting of emissions data and penalties for non-compliance.\n\nCritics argue the targets, while ambitious, may still fall short of what scientists say is needed to limit warming to 1.5°C above pre-industrial levels.",
    category: "Politics",
    image: "https://images.unsplash.com/photo-1569163139394-de4e4f4e1334?w=600&h=400&fit=crop",
    date: "2025-04-09",
    bias: "Slight Bias",
    mood: "Positive",
    confidence: 88,
    isBreaking: true,
  },
  {
    id: "3",
    title: "Champions League Quarter-Finals Deliver Stunning Upsets",
    summary: "Underdogs triumph as two top-seeded teams are eliminated in dramatic fashion.",
    content: "The Champions League quarter-finals produced two of the most dramatic upsets in recent tournament history. A last-minute goal from an unlikely source sent the defending champions packing, while another underdog team overcame a two-goal deficit to advance.\n\nFans across Europe were treated to six goals across two matches, with standout individual performances from several young players making their mark on the biggest stage.\n\nThe draw for the semi-finals is scheduled for Friday, with the remaining four teams each having legitimate claims to lifting the trophy.",
    category: "Sports",
    image: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=600&h=400&fit=crop",
    date: "2025-04-08",
    bias: "Neutral",
    mood: "Positive",
    confidence: 92,
  },
  {
    id: "4",
    title: "New Study Reveals Benefits of Intermittent Fasting",
    summary: "Comprehensive research shows significant health improvements from structured fasting patterns.",
    content: "A comprehensive study involving over 10,000 participants has found that structured intermittent fasting can lead to significant improvements in cardiovascular health, metabolic markers, and cognitive function.\n\nThe study, conducted over three years, compared various fasting protocols and found that a 16:8 pattern yielded the most consistent benefits. Participants showed reduced inflammation, improved insulin sensitivity, and better sleep quality.\n\nResearchers emphasize that the approach isn't suitable for everyone and recommend consulting healthcare providers before starting any fasting regimen.",
    category: "Health",
    image: "https://images.unsplash.com/photo-1505576399279-565b52d4ac71?w=600&h=400&fit=crop",
    date: "2025-04-08",
    bias: "Neutral",
    mood: "Positive",
    confidence: 90,
  },
  {
    id: "5",
    title: "Stock Markets Hit Record Highs Amid Tech Rally",
    summary: "Major indices surge as technology sector leads broad-based market gains.",
    content: "Global stock markets reached new all-time highs as a powerful rally in technology shares lifted major indices. The S&P 500 gained 2.3% in its best single-day performance in months, driven by strong earnings reports from several mega-cap tech companies.\n\nAnalysts point to improving economic data, cooling inflation, and optimism around AI-driven productivity gains as key factors behind the rally. Trading volumes were significantly above average.\n\nHowever, some market watchers warn that valuations are stretched and that the narrow leadership of the rally could be a cause for concern.",
    category: "Business",
    image: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=600&h=400&fit=crop",
    date: "2025-04-07",
    bias: "Slight Bias",
    mood: "Positive",
    confidence: 85,
  },
  {
    id: "6",
    title: "Cybersecurity Threats Escalate Globally",
    summary: "Governments and corporations face increasing sophisticated cyber attacks targeting critical infrastructure.",
    content: "A wave of sophisticated cyber attacks has targeted critical infrastructure across multiple countries, prompting emergency responses from national security agencies. The attacks, attributed to state-sponsored groups, exploited previously unknown vulnerabilities in widely-used software.\n\nSeveral major corporations reported data breaches affecting millions of users, while government agencies scrambled to patch systems. Cybersecurity experts warn that the attacks represent a new level of sophistication.\n\nIn response, several nations have announced increased cybersecurity budgets and new international cooperation frameworks to combat the growing threat.",
    category: "Tech",
    image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=600&h=400&fit=crop",
    date: "2025-04-07",
    bias: "Neutral",
    mood: "Negative",
    confidence: 91,
  },
  {
    id: "7",
    title: "Olympics 2028: Los Angeles Unveils Venue Plans",
    summary: "The organizing committee reveals ambitious plans for sustainable, tech-enhanced Olympic venues.",
    content: "The Los Angeles 2028 Olympic organizing committee has unveiled detailed plans for its competition venues, promising the most technologically advanced and sustainable Games in history.\n\nThe plans include solar-powered stadiums, AI-assisted judging systems, and immersive fan experiences using augmented reality. Most venues will use existing infrastructure, keeping construction costs lower than recent editions.\n\nAthletes will compete across iconic LA locations, with beach volleyball at Santa Monica and surfing at Malibu. The committee expects to generate $5 billion in economic activity for the region.",
    category: "Sports",
    image: "https://images.unsplash.com/photo-1461896836934-bd45ba8a0e28?w=600&h=400&fit=crop",
    date: "2025-04-06",
    bias: "Neutral",
    mood: "Positive",
    confidence: 87,
  },
  {
    id: "8",
    title: "Mental Health Crisis Among Young Adults Deepens",
    summary: "New report highlights alarming rise in anxiety and depression rates among 18-25 year olds.",
    content: "A comprehensive report from the World Health Organization reveals that anxiety and depression rates among young adults aged 18-25 have increased by 35% over the past three years. The report cites social media, economic uncertainty, and climate anxiety as primary contributors.\n\nExperts recommend expanded access to mental health services, workplace mental health programs, and digital wellness initiatives. Several countries have announced increased funding for youth mental health programs.\n\nThe report also highlights promising interventions, including peer support networks and AI-powered therapy tools that have shown positive results in pilot programs.",
    category: "Health",
    image: "https://images.unsplash.com/photo-1493836512294-502baa1986e2?w=600&h=400&fit=crop",
    date: "2025-04-06",
    bias: "Neutral",
    mood: "Negative",
    confidence: 93,
  },
  {
    id: "9",
    title: "Quantum Computing Milestone: 1000-Qubit Processor Unveiled",
    summary: "A major tech company demonstrates a 1000-qubit quantum processor, breaking previous records.",
    content: "In a breakthrough that could accelerate the quantum computing era, researchers have successfully demonstrated a 1000-qubit quantum processor that maintains coherence for record-breaking durations.\n\nThe achievement represents a significant step toward practical quantum computing applications, from drug discovery to cryptography.\n\nIndustry experts predict commercial quantum computers could be available within the next decade.",
    category: "Tech",
    image: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600&h=400&fit=crop",
    date: "2025-04-05",
    bias: "Neutral",
    mood: "Positive",
    confidence: 89,
    relatedTo: "1",
  },
  {
    id: "10",
    title: "Renewable Energy Investments Surge to Record $500B",
    summary: "Global investment in clean energy reaches unprecedented levels, led by solar and wind projects.",
    content: "Global investment in renewable energy has reached a record $500 billion in the first quarter of 2025, driven by declining costs and supportive government policies.\n\nSolar energy led the charge with $200 billion in new investments, followed by wind power at $150 billion. Battery storage technology also saw significant growth.\n\nAnalysts expect the trend to accelerate as more countries implement their climate commitments.",
    category: "Business",
    image: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=600&h=400&fit=crop",
    date: "2025-04-05",
    bias: "Slight Bias",
    mood: "Positive",
    confidence: 86,
    relatedTo: "2",
  },
];

const todaySummary = [
  "AI reasoning model breaks new ground in human-level problem solving",
  "Global climate summit yields historic 40% carbon reduction commitment",
  "Champions League upsets shake European football landscape",
  "Tech rally drives stock markets to record highs worldwide",
  "Cybersecurity agencies on high alert after coordinated infrastructure attacks",
];

const timelineEvents = [
  { year: 1990, title: "World Wide Web Goes Public", description: "Tim Berners-Lee introduces the World Wide Web, forever changing how humans access information.", category: "Tech", details: "The first web server and browser were created at CERN. The web was initially designed for scientists to share research papers, but its potential for broader use was quickly recognized." },
  { year: 1991, title: "Soviet Union Dissolves", description: "The dissolution of the USSR marks the end of the Cold War era.", category: "Politics", details: "On December 26, 1991, the Soviet Union officially ceased to exist, ending nearly seven decades of communist rule and reshaping the global political landscape." },
  { year: 1994, title: "Nelson Mandela Becomes President", description: "South Africa holds its first democratic elections, electing Nelson Mandela.", category: "Politics", details: "After 27 years in prison, Mandela won the election in a landslide, marking the end of apartheid and beginning a new era for South Africa." },
  { year: 1997, title: "Deep Blue Defeats Kasparov", description: "IBM's Deep Blue becomes the first computer to defeat a reigning world chess champion.", category: "Tech", details: "The match was a watershed moment in AI history, demonstrating that machines could outperform humans in complex strategic thinking." },
  { year: 1998, title: "Google Founded", description: "Larry Page and Sergey Brin launch Google from a garage in Menlo Park.", category: "Tech", details: "What started as a Stanford research project became the world's most popular search engine and one of the most valuable companies in history." },
  { year: 2000, title: "Dot-com Bubble Bursts", description: "The NASDAQ crashes as inflated tech stock valuations collapse.", category: "Business", details: "The crash wiped out $5 trillion in market value of technology companies between March 2000 and October 2002." },
  { year: 2001, title: "September 11 Attacks", description: "Terrorist attacks on the World Trade Center and Pentagon reshape global politics.", category: "Politics", details: "The attacks led to the War on Terror, significant changes in national security policies worldwide, and lasting geopolitical consequences." },
  { year: 2004, title: "Facebook Launches", description: "Mark Zuckerberg launches Facebook from his Harvard dorm room.", category: "Tech", details: "Initially limited to Harvard students, Facebook rapidly expanded to become the world's largest social network with billions of users." },
  { year: 2007, title: "iPhone Revolutionizes Mobile", description: "Apple unveils the first iPhone, transforming the smartphone industry.", category: "Tech", details: "The iPhone combined a phone, an iPod, and an internet communicator into one device, creating the modern smartphone era." },
  { year: 2008, title: "Global Financial Crisis", description: "The collapse of Lehman Brothers triggers a worldwide economic recession.", category: "Business", details: "The crisis led to massive government bailouts, new financial regulations, and a global recession that affected millions of people." },
  { year: 2010, title: "Arab Spring Begins", description: "A wave of pro-democracy protests sweeps across the Middle East and North Africa.", category: "Politics", details: "Starting in Tunisia, the movement spread to Egypt, Libya, Syria, and other countries, leading to regime changes and ongoing conflicts." },
  { year: 2012, title: "Higgs Boson Discovered", description: "CERN confirms the discovery of the Higgs boson particle.", category: "Tech", details: "The discovery confirmed a key prediction of the Standard Model of physics and earned Peter Higgs and François Englert the Nobel Prize." },
  { year: 2014, title: "Ice Bucket Challenge Goes Viral", description: "Social media campaign raises $115M for ALS research.", category: "Health", details: "The viral challenge demonstrated the power of social media for charitable causes and funded significant advances in ALS research." },
  { year: 2016, title: "AlphaGo Defeats Lee Sedol", description: "Google DeepMind's AI defeats the world Go champion in a historic match.", category: "Tech", details: "The victory was considered a major milestone in AI, as Go was thought to be too complex for computers to master." },
  { year: 2020, title: "COVID-19 Pandemic", description: "A global pandemic disrupts life worldwide, accelerating digital transformation.", category: "Health", details: "The pandemic caused millions of deaths, reshaped work culture, and accelerated adoption of remote work, telemedicine, and digital services." },
  { year: 2022, title: "ChatGPT Launches", description: "OpenAI releases ChatGPT, sparking an AI revolution in consumer technology.", category: "Tech", details: "ChatGPT reached 100 million users in just two months, making it the fastest-growing consumer application in history." },
  { year: 2024, title: "Paris Olympics Captivates World", description: "The 2024 Summer Olympics showcase spectacular events across iconic Parisian venues.", category: "Sports", details: "The Games were praised for their unique use of Paris landmarks as venues and their focus on sustainability and inclusion." },
];

const chatResponses = {
  "summarize today's news": "Here's your daily summary:\n\n📰 **AI Breakthrough** — A new AI model has achieved human-level reasoning across multiple domains, marking a significant milestone.\n\n🌍 **Climate Summit** — 195 nations agreed to 40% carbon reduction targets in a historic deal.\n\n⚽ **Champions League** — Major upsets as two top-seeded teams were eliminated.\n\n📈 **Markets** — Tech rally pushed stock indices to record highs.\n\n🔒 **Cybersecurity** — Coordinated attacks on critical infrastructure prompted global alert.",
  "what happened in 2020?": "**2020 was dominated by the COVID-19 pandemic:**\n\n🦠 The virus spread globally, causing millions of infections and deaths\n\n🏠 Lockdowns transformed daily life — remote work became the norm\n\n💉 Vaccine development happened at unprecedented speed\n\n📱 Digital transformation accelerated by years in months\n\n📉 Global economy experienced sharp contraction followed by gradual recovery\n\nIt was a year that fundamentally changed how we live, work, and interact.",
  "tech news last decade": "**Key tech developments (2015-2025):**\n\n🤖 **2016** — AlphaGo defeats world Go champion\n\n📱 **2017** — iPhone X introduces Face ID\n\n🔗 **2018** — Blockchain and crypto surge\n\n⚡ **2019** — 5G networks begin rolling out\n\n🏠 **2020** — Remote work revolution\n\n🎨 **2022** — AI art and ChatGPT launch\n\n🥽 **2023** — Apple Vision Pro announced\n\n🧠 **2024** — AI agents become mainstream\n\n🚀 **2025** — AI achieves human-level reasoning",
  default: "That's a great question! Based on my knowledge, here's what I can tell you:\n\nThis topic has seen significant developments over the years. The key trends include technological innovation, shifting geopolitical dynamics, and evolving social norms.\n\nWould you like me to dive deeper into any specific aspect? You can also try asking about specific years, topics, or events!",
};

module.exports = { mockNews, todaySummary, timelineEvents, chatResponses };
